### ISSUE TITLE
Log errors to stderr

### ISSUE THREAD

**Issue by sstarcher** [arschles/envtpl#13]
My understanding is the use case is
`envtpl -in template > file`

Currently logging for errors is doing `fmt.Print()`
Which would cause the error to be logged into the file and not to show up in the script that is running envtpl.

It would be debugging easier to change the print statements to `fmt.Fprint(os.Stderr,)`

I'll give you a pull request with those changes if you agree.

**Comment by arschles** [comment]
@sstarcher 

> My understanding is the use case is `envtpl -in template > file`

Yep, that was my original intention

> It would be debugging easier to change the print statements to fmt.Fprint(os.Stderr,)

Totally, :+1:

> I'll give you a pull request with those changes if you agree.

Yep, I agree. Looking forward to the PR!

**Comment by sstarcher** [comment]
#14
